In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

print(arr)

print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr.ndim)

1


In [5]:
# à compléter
matrice = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
# contrôle - NE PAS MODIFIER
matrice.ndim == 2

True

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr[0])

1


In [10]:
# à compléter
x = arr[1]

print(x)

2


In [11]:
# contrôle - NE PAS MODIFIER
x == 2

True

In [12]:
# à compléter
somme = arr[2] + arr[3]

print(somme)

7


In [13]:
# contrôle - NE PAS MODIFIER
somme == 7

True

In [14]:
arr[1:3]

array([2, 3])

In [19]:
# à compléter
tranche1 = arr[1:4]

tranche1

array([2, 3, 4])

In [20]:
# contrôle - NE PAS MODIFIER
tranche1 == np.array([2,3,4])

array([ True,  True,  True])

In [21]:
# à compléter
tranche2 = arr[2:6:2]

tranche2

array([3, 5])

In [23]:
# contrôle - NE PAS MODIFIER
tranche2 == np.array([3,5])

array([ True,  True])

In [24]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr + 1)
print(1 + arr)

[2 3 4 5 6 7]
[2 3 4 5 6 7]


In [25]:
liste = [1, 2, 3, 4, 5, 6]

print(liste + 1)

Traceback (most recent call last):
  File "<input>", line 3, in <module>
TypeError: can only concatenate list (not "int") to list


Error: 

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(2*arr)
print(arr*2)

[ 2  4  6  8 10 12]
[ 2  4  6  8 10 12]


In [27]:
liste = [1, 2, 3, 4, 5, 6]

print(2*liste)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]


In [29]:
# à compléter
arr = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0])

carre = arr**2
cube  = 2*arr**3 + 1
expo  = np.exp(arr)
sinus = np.cos(np.pi*arr)

print(carre)
print(cube)
print(expo)
print(sinus)

[ 1.  4.  9. 16. 25. 36.]
[  3.  17.  55. 129. 251. 433.]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[-1.  1. -1.  1. -1.  1.]
