# CN0 - Utilisation des tableaux numpy en physique 

Objectif : *« Réviser l'utilisation des tableaux numpy pour représenter des grandeurs physiques. »*

Lien capytale : https://capytale2.ac-paris.fr/web/c/6721-1761691

Lien corrigé : https://capytale2.ac-paris.fr/web/c/0af9-1761738

## A) Introduction

NumPy est utilisé pour travailler avec des tableaux. L'objet tableau dans NumPy est appelé ndarray. 

Les tableaux sont très utiles en physique car on peut les manipuler très simplement dans les expressions mathématiques.

Nous pouvons créer un objet NumPy ndarray en utilisant la fonction array() appliquée à une liste.

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

print(arr)

print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


Dans les tableaux, une dimension correspond à un niveau de profondeur du tableau (tableaux imbriqués). 

Nous créons ci-dessous un tableau de dimension 1. La méthode ndim renvoit la dimension d'un tableau.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr.ndim)

Nous pouvons aussi créer des tableaux de dimension 2 (matrice) en donnant une liste de liste en argument de array(). 

>**Question 1**
>
>  Compléter le code ci-dessous pour créer une matrice contenant les 2 lignes [1, 2, 3] et [4, 5, 6]. 

In [ ]:
# à compléter
matrice = ...

In [ ]:
# contrôle - NE PAS MODIFIER
print(matrice.ndim) == 2

## B) Indexation et découpage en tranches de tableaux 

Vous pouvez accéder à un élément de tableau en vous référant à son indice, comme pour une liste.

Les indices des tableaux NumPy commencent par 0, ce qui signifie que le premier élément a l'indice 0, le second l'indice 1, etc.

On peut obtenir le premier élément du tableau avec la syntaxe suivante.

In [ ]:
print(arr[0])

>**Question 2**
>
>  Compléter le code suivant pour afficher le second élément du tableau `arr`.

In [ ]:
# à compléter
x = arr[...]

print(x)

In [ ]:
# contrôle - NE PAS MODIFIER
x == 2

>**Question 3**
>
>  Récupérez les troisième et quatrième éléments du tableau `arr` et additionnez-les.

In [ ]:
# à compléter
somme = arr[...] + arr[...]

print(somme)

In [ ]:
# contrôle - NE PAS MODIFIER
somme == 7

Le découpage en tranches en python (slicing) consiste à prendre des éléments d'un indice i donné à un autre indice j donné. Nous prenons la tranche d'un tableau comme ceci : [i:j]. Nous pouvons également définir le pas, comme ceci : [i:j:pas]. 

Nous pouvons prendre la tranche du tableau arr des indices 1 (inclus) à 3 (exclu) de la façon suivante.

In [ ]:
arr[1:3]

>**Question 4**
>
> Prendre la tranche du tableau `arr` des indices 1 (inclus) à 4 (exclu).

In [ ]:
# à compléter
tranche1 = arr[...]

print(tranche1)

In [ ]:
# contrôle - NE PAS MODIFIER
tranche1 == np.array([2,3,4])

>**Question 5**
>
> Prendre la tranche du tableau `arr` qui contient tous les indices pairs entre 2 (inclus) à 6 (exclu).

In [ ]:
# à compléter
tranche2 = arr[...]

print(tranche2)

In [ ]:
# contrôle - NE PAS MODIFIER
tranche1 == np.array([3,5])

## C) Manipulation mathématique de tableaux

L'intérêt des tableaux NumPy est qu'on peut les manipuler mathématiquement comme des nombres. 

Cela inclut les opérations suivantes : effectuer des additions ou multiplications avec un nombre, 
ou appliquer une fonction au tableau (cos, sin, exp, ln, etc.).

Avec la syntaxe suivante, chaque entrée du tableau est additionné avec le nombre 1.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr + 1)
print(1 + arr)

La même opération effectuée sur une liste renvoit une erreur !

In [ ]:
liste = [1, 2, 3, 4, 5, 6]

print(liste + 1)

De même, on peut multiplier chaque entrée du tableau avec le nombre 2.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(2*arr)
print(arr*2)

La même opération effectuée sur une liste renvoie la liste concaténée avec elle-même.

In [ ]:
liste = [1, 2, 3, 4, 5, 6]

print(2*liste)

>**Question 6**
>
> Compléter le code suivant pour effectuer les opérations suivantes sur le tableau arr :
    - éléver au carré ;
    - éléver au cube puis multiplier par 2 et ajouter 1 ;
    - prendre l'exponentielle (np.exp) ;
    - multiplier par 2 pi (np.pi) et prendre le cosinus (np.cos).

In [ ]:
# à compléter
arr = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0])

carre = ...
cube  = ...
expo  = ...
sinus = ...

print(carre)
print(cube)
print(expo)
print(sinus)

## D) Tableaux régulièrement espacés 

Il arrive souvent qu'on ait besoin de créer un tableau constitué d'un nombre N connu de valeurs réelles régulièrement espacées.

La syntaxe pour créer de tels tableaux utilise la fonction linspace. Par exemple, pour créer un tableau comprenant les nombres entiers de 1 à 10, on peut écrire la chose suivante.

In [8]:
N   = 10

arr = np.linspace(1, 10, N)

print(arr)
print(type(arr))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


>**Question 7**
>
> Créer un tableau régulièrement espacé comprenant tous les demi-entiers de 0 à 10 (0, 0.5, 1, ...). 

In [ ]:
# à compléter
arr = ...

print(arr)

In [ ]:
# contrôle - NE PAS MODIFIER
arr == np.array([0.0,0.5,1.0,1.5,2.0,2.5,3.0,3.5,4.0,4.5,5.0,5.5,6.0,6.5,7.0,7.5,8.0,8.5,9.0,9.5,10])

Un autre type de tableaux souvent utilisé est les tableaux remplis de zéros. Ces tableaux servent souvent pour initialiser un tableau avant de calculer ses valeurs. 

On utilise pour cela la fonction zeros.

In [9]:
N   = 10

arr = np.zeros(N)

print(arr)
print(type(arr))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


>**Question 8**
>
>  Compléter le code ci-dessous pour créer un tableau rempli de 5 zéros.

In [ ]:
# à compléter
arr == ...

print(arr)

In [ ]:
# contrôle - NE PAS MODIFIER
arr == np.array([0.,0.,0.,0.,0.])